### ISSUE TITLE
MongoDB Collection.insert and Collection.update are deprecated

### ISSUE THREAD

**Issue by alexcrist** [JonnyBurger/tics#1]
Hello Jonny, 

I'm using `mongodb@3.2.7` and `tics` in my project (Joro). Getting these warnings originating from `tics`.
```
DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
```
Thanks,
Alex

**Comment by JonnyBurger** [comment]
Hey Alex,

I published a new version `tics@2.0.0-alpha.13` which fixes this and some other problems - would you like to try it out?
